#!/usr/bin/python3
""" 5-main """
from models.rectangle import Rectangle
from models.base import Base
if __name__ == "__main__":
    b1 = Base()
    print(b1.id)
    b2 = Base()
    print(b2.id)
    b3 = Base()
    print(b3.id)
    b4 = Base(12)
    print(b4.id)
    b5 = Base()
    print(b5.id)
    r1 = Rectangle(4, 6, 2, 1, 12)
    print(r1)
    r2 = Rectangle(5, 5, 1)
    print(r2)
    r1 = Rectangle(4, 6)
    r1.display()
    print("---")
    r1 = Rectangle(2, 2)
    r1.display()
    r1 = Rectangle(3, 2)
    print(r1.area())
    r2 = Rectangle(2, 10)
    print(r2.area())
    r3 = Rectangle(8, 7, 0, 0, 12)
    print(r3.area())
    r1 = Rectangle(2, 3, 2, 2)
    r1.display()
    print("---")
    r2 = Rectangle(4, 4, 8, 5)
    r2.display()
